### ISSUE TITLE
export 'set' (imported as 'set$1') was not found in 'vue-demi'

### ISSUE THREAD

**Issue by sebastianjung** [vueuse/vueuse#1733] opened 2022-07-01 13:49 UTC
### Describe the bug

terminal throws multiple warnings when running quasar in dev mode:

export 'set' (imported as 'set') was not found in 'vue-demi'
export 'del' (imported as 'del') was not found in 'vue-demi'
export 'default' (imported as 'Vue') was not found in 'vue'
export 'default' (reexported as 'Vue') was not found in 'vue' 
export 'set' (imported as 'set$1') was not found in 'vue-demi'

it seems the new version of vue-demi does not export some of the exports used by vueuse anymore:
https://github.com/vueuse/vue-demi/releases/tag/v0.13.1

### Reproduction

tried to reproduce on codepen but error is not available through cdn i guess because it's a build/bundling problem?

### System Info

```Shell
version used:
"@vueuse/core": "8.7.5"
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment] 2022-07-08 05:57
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2022-07-08 05:57 UTC

**Comment by vidal7** [comment] 2024-10-03 22:53
@sebastianjung , I face the same issue. Did you find a solution?

**Comment by vidal7** [comment] 2024-10-04 11:31
Finally, I had this problem switching branches from Vue 2.7 to Vue 3 with compat build. What resolved my problem was to reinstall @vueuse/core.
