### ISSUE TITLE
Problem when using useVModel with a boolean value

### ISSUE THREAD

**Issue by oliviervanbulck** [vueuse/vueuse#2784] opened 2023-02-17 14:05 UTC
### Describe the bug

I use useVModel() in a boolean-type input field. When I use the normal way, the value is not reactive. I use the value returned from useVModel in templates to calculate classes, but this won't work.

```
const innerValue = useVModel(props, 'modelValue', emit);
```

The innerValue variable is not reactive and can't be used.

When I change the options to { passive: true }, this value is reactive, but it won't emit @update:model-value when the new value is false.

### Reproduction

-

### System Info

```Shell
System:
    OS: macOS 13.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz
    Memory: 267.65 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 109.0.5414.87
    Firefox: 107.0.1
    Safari: 16.2
  npmPackages:
    @vueuse/core: ^9.10.0 => 9.10.0 
    vue: 3.3.0-alpha.4 => 3.3.0-alpha.4
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by oliviervanbulck** [comment] 2023-02-20 07:51
The type returned from useVModel() seems to be `string | true`.

**Comment by antfu** [comment] 2023-02-20 11:12
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-02-20 11:12 UTC
