### ISSUE TITLE
Question about using @vueuse/integrations

### ISSUE THREAD

**Issue by mishka86** [vueuse/vueuse#1021] opened 2021-12-09 01:37 UTC
When ssr:true in nuxt.js environment
I tride to install because I wanted to use the useAxios function in @vueuse/integrations
However, the message below was exposed.
Cannot find module '@vueuse/integrations/useAxios' 

npm i @vueuse/integrations
npm i axios

Is there anything else i need to do other than the above actions?

**Comment by checkwoodson** [comment] 2022-01-19 05:44
you need import 
For example:
import {useAxios} from '@vueuse/integrations/useAxios'

**Comment by antfu** [comment] 2022-01-21 08:32
We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.

**Closed by antfu** 2022-01-21 08:32 UTC
