### ISSUE TITLE
useDropZone not working in safari

### ISSUE THREAD

**Issue by yurenklimbu** [vueuse/vueuse#3925] opened 2024-04-15 10:38 UTC
### Describe the bug

useDropZone not working in safari after dataTypes set.

"I copied and pasted example code for testing, but it doesn't work in the Safari browser. It works without dataTypes. Can you help me fix this?

```
<script setup lang="ts">
import { ref } from 'vue'
import { useDropZone } from '@vueuse/core'

const filesData = ref<{ name: string; size: number; type: string; lastModified: number }[]>([])

function onDrop(files: File[] | null) {
  filesData.value = []
  if (files) {
    filesData.value = files.map((file) => ({
      name: file.name,
      size: file.size,
      type: file.type,
      lastModified: file.lastModified
    }))
  }
}

const dropZoneRef = ref<HTMLElement>()

const { isOverDropZone } = useDropZone(dropZoneRef, {
  dataTypes: ['image/png'],
  onDrop
})
</script>
```

### Reproduction

https://stackblitz.com/edit/vitejs-vite-ard9vw?file=src%2FApp.vue&terminal=dev

### System Info

```Shell
System:
    OS: macOS 14.4.1
    CPU: (11) arm64 Apple M3 Pro
    Memory: 129.45 MB / 18.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.6.1 - /opt/homebrew/bin/node
    npm: 10.2.4 - /opt/homebrew/bin/npm
    bun: 1.1.2 - ~/.bun/bin/bun
    Watchman: 2023.12.04.00 - /opt/homebrew/bin/watchman
  Browsers:
    Brave Browser: 123.1.64.122
    Chrome: 123.0.6312.124
    Edge: 123.0.2420.97
    Safari: 17.4.1
  npmPackages:
    @vueuse/core: ^10.9.0 => 10.9.0
    vue: ^3.4.21 => 3.4.21
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by TheVaan** [comment] 2024-04-22 11:08
I can confirm, in Safari `isOverDropZone` is not resolving to `true`.

**Comment by DylanThomasFr** [comment] 2024-05-15 08:19
It is a duplicate of this one : https://github.com/vueuse/vueuse/issues/3573

I have the same issue as well. Tried to have a look at the code but can't figure out a solution

**Comment by 2nofa11** [comment] 2024-12-20 04:56
This issue is actively being discussed in https://github.com/vueuse/vueuse/issues/3573, so please track that issue instead.
I will close this issue.

**Closed by 2nofa11** 2024-12-20 04:56 UTC
Labels: needs reproduction
