### ISSUE TITLE
`useRouteQuery` serializer

### ISSUE THREAD

**Issue by Shinigami92** [vueuse/vueuse#3693] opened 2024-01-04 12:07 UTC
### Clear and concise description of the problem

We having filters containing `Date`s.
Now our URLs contain the string representation of such dates and we want them in ISO 8601 format

```diff
- .../dashboard?search&start=Thu+Jan+04+2024+00:00:00+GMT%2B0100+(Central+European+Standard+Time)&end=Thu+Jan+04+2024+23:59:59+GMT%2B0100+(Central+European+Standard+Time)
+ .../dashboard?search&start=2024-01-03T23:00:00.000Z&end=2024-01-04T22:59:59.000Z
```

### Suggested solution

allow passing a `serializer`, could be same as for `useStorage`

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Glandos** [comment] 2024-06-14 09:51
Duplicate of #3929 

This ticket is anterior, but #3929 has a better description.

**Comment by ilyaliao** [comment] 2024-12-19 03:32
Based on #3929  being closed, I will also close this. Feel free to reopen it if needed.

**Closed by ilyaliao** 2024-12-19 03:32 UTC
Labels: enhancement
