### ISSUE TITLE
use tryOnBeforeUnmount in jsx

### ISSUE THREAD

**Issue by fabin5** [vueuse/vueuse#855] opened 2021-10-19 02:10 UTC
it's can not work when I use 'tryOnBeforeUnmount' in a JSX function.

eg:

```
export default function useSelections() {
  // .....
  console.log(getCurrentInstance());
  tryOnBeforeUnmount(() => {
    // do something
  });
```

xxx.jsx
```
  const { ... } = useSelections();

  return (
    <div>
     .....
   </div>
```

result:
![image](https://user-images.githubusercontent.com/5445667/137832127-13d7ec46-9da6-4541-a7cd-6f8f7495729d.png)

**Comment by antfu** [comment] 2021-10-20 00:50
We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.

**Closed by antfu** 2021-10-20 00:50 UTC
