### ISSUE TITLE
Algolia search on the main page broken

### ISSUE THREAD

**Issue by martinszeltins** [vueuse/vueuse#2755] opened 2023-02-11 11:30 UTC
### Describe the bug

The search seems to be broken and finds nothing:

![image](https://user-images.githubusercontent.com/34019878/218255611-809b14e3-71fd-4eca-b6d8-fd50c09a7c97.png)

### Reproduction

No info

### System Info

```Shell
No info
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ojvribeiro** [comment] 2023-02-12 04:57
Duplicate of #2742.

**Comment by brc-dd** [comment] 2023-02-14 10:31
Should be fixed now.

**Closed** 2023-02-14 13:05 UTC
