### ISSUE TITLE
ts 解析报错 与 "@vueuse/core": "^7.1.2" , "vue": "^3.2.20" , "@vitejs/plugin-vue-jsx": "^1.1.6",

### ISSUE THREAD

**Issue by fufengren** [vueuse/vueuse#1001] opened 2021-12-02 07:51 UTC
node_modules/@vueuse/shared/index.d.ts:35:5 - error TS1131: Property or signature expected.

35     get value(): T;
       ~~~

node_modules/@vueuse/shared/index.d.ts:35:9 - error TS1005: ';' expected.

35     get value(): T;
           ~~~~~

node_modules/@vueuse/shared/index.d.ts:35:16 - error TS1005: ';' expected.

35     get value(): T;
                  ~

node_modules/@vueuse/shared/index.d.ts:36:9 - error TS1005: ';' expected.

36     set value(value: T | null | undefined);
           ~~~~~

node_modules/@vueuse/shared/index.d.ts:36:20 - error TS1005: ',' expected.

36     set value(value: T | null | undefined);
                      ~

node_modules/@vueuse/shared/index.d.ts:37:1 - error TS1128: Declaration or statement expected.

37 };
   ~

**Comment by antfu** [comment] 2021-12-02 08:15
We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.

**Closed by antfu** 2021-12-02 08:15 UTC
