### ISSUE TITLE
use tsx: The hook can get the value only after onMounted

### ISSUE THREAD

**Issue by KleinovVir** [vueuse/vueuse#1914] opened 2022-07-14 10:02 UTC
### Describe the bug

use tsx: The hook can get the value only after onMounted
**No, it's undefined in onmounted**
```js
import { defineComponent, onMounted, reactive } from "vue";
import { useMouse, usePreferredDark } from "@vueuse/core";
import styles from "./index.module.scss";
interface IMouse {
  x: number;
  y: number;
  isDark?: boolean;
  getLocalPosition?: (point: number) => void;
}
export default defineComponent({
  setup() {
    const mouse = reactive<IMouse>({ x: 0, y: 0, isDark: false });
    const { x_1, y_1 } = useMouse(); // **x_1, y_1undefined**
    onMounted(() => {
      const { x, y } = useMouse();
      (mouse.isDark as any) = usePreferredDark();
      (mouse.x as any) = x;
      (mouse.y as any) = y;
    });
    return () => (
      <>
        <div class={styles.container}>
          <span>{mouse.x}</span>
          <span>:{String(mouse.isDark)}:</span>
          <span>{mouse.y}</span>
        </div>
      </>
    );
  },
});
```

### Reproduction

undefined

### System Info

```Shell
{ useMouse, usePreferredDark } from "@vueuse/core"
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by chaii3** [comment] 2022-07-20 17:41
I'm sorry but I can't understand your problem. If you're talking about ```const { x_1, y_1 } = useMouse()``` you always will get undefined because there're not keys like this.

**Comment by antfu** [comment] 2022-07-21 12:03
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2022-07-21 12:03 UTC

**Comment by KleinovVir** [comment] 2022-07-22 02:40
> 的键
Sorry, I changed it when I copied it here. I'm afraid of being misunderstood. I didn't pay attention to it. It's not enough. Is it x, y or print undefined in the code
