### ISSUE TITLE
useInfiniteScroll v10 behavior differs from v9 - Scrolling to the edge triggers an infinite event.

### ISSUE THREAD

**Issue by sondh0127** [vueuse/vueuse#3019] opened 2023-04-23 15:24 UTC
### Describe the bug

useInfiniteScroll v10 behavior is different with v9

https://user-images.githubusercontent.com/62163604/233847985-dd49eeef-93c5-47df-937c-973c3ec9ca9c.mov

Scrolling to the edge triggers an infinite event.

### Reproduction

https://github.com/sondh0127/my-vitesse-app-useInfiniteScroll

### System Info

```Shell
System:
    OS: macOS 13.3.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 59.34 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.13.0 - ~/Library/Caches/fnm_multishells/94889_1682258323298/bin/node
    Yarn: 1.22.19 - ~/Library/Caches/fnm_multishells/94889_1682258323298/bin/yarn
    npm: 8.19.3 - ~/Library/Caches/fnm_multishells/94889_1682258323298/bin/npm
  Browsers:
    Brave Browser: 112.1.50.121
    Chrome: 112.0.5615.137
    Safari: 16.4
  npmPackages:
    @vueuse/core: 10.1.0 => 10.1.0
    @vueuse/head: ^1.1.26 => 1.1.26
    vue: ^3.2.47 => 3.2.47
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sondh0127** [comment] 2023-04-24 03:43
Thank you, but how do I get the v9 behavior?

> The behavior difference is expected since we introduced a breaking change. It looks ok to me, and I am actually not able to repro the infinite events. Can you share more details?

**Comment by JJBocanegra** [comment] 2023-04-24 17:55
It happened to me also that by default is constantly executing the method since upgrading it to v10

<img width="543" alt="image" src="https://user-images.githubusercontent.com/5797636/234077376-6874e848-cf7a-48f3-aba8-847115d8fc84.png">

**Comment by smallnine9** [comment] 2023-04-25 15:50
@sondh0127 @JJBocanegra 
it's because the version of vueuse you are using is not the latest.
The latest vueuse/core does not have this problem:
```
vueDemi.watch(() => state.arrivedState[direction], async (v) => {
    var _a2, _b2;
    if (v) {
      const elem = shared.toValue(element);
      const previous = {
        height: (_a2 = elem == null ? void 0 : elem.scrollHeight) != null ? _a2 : 0,
        width: (_b2 = elem == null ? void 0 : elem.scrollWidth) != null ? _b2 : 0
      };
      await onLoadMore(state);
      if (options.preserveScrollPosition && elem) {
        vueDemi.nextTick(() => {
          elem.scrollTo({
            top: elem.scrollHeight - previous.height,
            left: elem.scrollWidth - previous.width
          });
        });
      }
    }
  });
```
the old version which has problem:
 ```
 vueDemi.watch(
    () => [state.arrivedState[direction], shared.toValue(element)],
    checkAndLoad,
    { immediate: true }
  );
```
you can check the @vueuse/core in your node_modules

**Comment by smallnine9** [comment] 2023-04-25 15:50
@antfu we can close this

**Comment by Poloten** [comment] 2023-04-26 12:40
This fix doesn't work correctly, infinite loop exist, because scroll doesnt save previous position to bottom.

**Comment by martynchamberlin** [comment] 2023-04-26 17:45
Looks like there's a secondary aspect to this regression too, from what I can tell: if the callback passed in the second param to `useInfiniteScroll()` is async, then the callback _always_ gets re-called a second time, _immediately after the first promise has resolved._ Here's a very simple repo that reproduces the issue: https://github.com/martynchamberlin/vueuse-infinite-scroll  

A screencast to demonstrate what I'm talking about: 

https://user-images.githubusercontent.com/1827628/234659925-e9a997a0-7ad7-4e92-a26c-ff9c99054bee.mov

**Comment by scottbedard** [comment] 2023-04-26 17:47
I'm seeing this issue as well, [see repro here](https://github.com/vueuse/vueuse/compare/main...scottbedard:vueuse:main)

Going to look into this and see if I can find the problem

**Closed** 2023-05-02 00:49 UTC

**Comment by martynchamberlin** [comment] 2023-05-04 12:30
@simonbrunel I would hope not! Are you getting that behavior with this update?

**Comment by simonbrunel** [comment] 2023-05-04 13:47
If this update is available in v10.1.2, then yes: https://stackblitz.com/edit/vitejs-vite-m9chxu?file=src%2FApp.vue

Maybe `useInfiniteScroll` should check if the scroll height changed after calling `onLoadMore` (and avoid calling [`checkAndLoad`](https://github.com/vueuse/vueuse/blob/main/packages/core/useInfiniteScroll/index.ts#L79) if it did not changed). Or maybe `onLoadMore` could explicitly return `false` when nothing has been loaded, thus `useInfiniteScroll` can skip the `checkAndLoad` in the [finally callback](https://github.com/vueuse/vueuse/blob/main/packages/core/useInfiniteScroll/index.ts#L79).

**Comment by scottbedard** [comment] 2023-05-04 14:28
@simonbrunel calling _after_ the next tick is preferred because it gives the DOM to finish updating before re-measuring the containers. @antfu and I [discussed this here](https://github.com/vueuse/vueuse/pull/3030#discussion_r1178629206). As best I can tell, your stackblitz is behaving as expected. The `useInfiniteScroll` function has no context for what you're loading, or when it's complete. So upon completion, it checks the scroll position, and fires again if you're at the end. What I recommend doing is tracking the completed state yourself, and shutting things down when you want to stop. [Here is an example of what I'm describing](https://stackblitz.com/edit/vitejs-vite-zcvxfp?file=src/App.vue).

A future option might be for `useInfiniteScroll` to return a `disabled` ref, but this would essentially just be syntax sugar for what I linked above. But I'm not sure we want to create ref's that the end user might not need. Maybe we could also have `useInfiniteScroll` track the arrived state, and not load if it's `true` for a second time, but I could see that leading to situations where the infinite scroll becomes stuck 🤔

**Comment by simonbrunel** [comment] 2023-05-04 15:37
@scottbedard Thanks for your reply, your example works indeed and is easy enough to implement. And I agree, documenting the behavior at arrived state and adding that example would greatly help to workaround this issue. I still believe that this logic could be built-in in some way since it's easy to _not_ notice these extra infinite calls. I may be wrong, but I feel that most use cases would benefits from this auto-ending behavior.

> I see a similar problems with onLoadMore returning false, how would we start infinite scrolling again if we needed to?

My suggestion was that if `onLoadMore` returns `false`, `useInfiniteScroll` should stop trying to load more content (in the finally clause), **_unless_** the content changes or the user manually scrolls again the view (which would be [triggered by this watch](https://github.com/vueuse/vueuse/blob/main/packages/core/useInfiniteScroll/index.ts#L85) I guess). I don't think of case where the infinite scroll would be stuck with that approach.

**Comment by simonbrunel** [comment] 2023-05-04 17:37
Indeed, the returned value should be strictly `=== false` to avoid a breaking change. If returning `false` is not an acceptable solution, another approach could be a `canLoadMore` option, which is a bit comparable to `isDisabled`, except that it's an option.

```ts
const total = ref(42);
const data = ref([]);

useInfiniteScroll(
  el,
  async () => {
    data.value.push(...moreData)
  },
  {
    canLoadMore: () => data.length < total, // wrap it in a computed ref?!
    distance: 10 ,
  }
)
```

Then you can bind `canLoadMore` to the disabled logic you mentioned. If `canLoadMore` is undefined, we assume the current behavior (always call `onLoadMore`). But at this point, I'm not sure anymore which solution is better 😃

**Comment by mipawn** [comment] 2023-05-06 12:02
It seems more reasonable to use `document` instead of `window`
