### ISSUE TITLE
Vue2 + Vue composition-api,  useVirtualList cannot use

### ISSUE THREAD

**Issue by wenbintian** [vueuse/vueuse#1078] opened 2021-12-20 07:38 UTC

**Comment by wheatjs** [comment] 2021-12-21 05:46
We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.

**Closed by wheatjs** 2021-12-21 05:46 UTC
