### ISSUE TITLE
VueUse "No overload matches this call."

### ISSUE THREAD

**Issue by sdoerger** [vueuse/vueuse#913] opened 2021-11-09 15:40 UTC
I am not sure if that is an issue or if I am using it not correctly (since I am not to familiar with TypeScript, yet).

When I use useAxios, like in the demo ...:
```
import axios from 'axios'
import { useAxios } from '@vueuse/integrations/useAxios'

const instance = axios.create({
  baseURL: '/api'
})

const { data, isLoading, isFinished } = useAxios('/myUrl', instance)
```
... at `api` I get the Error at the bottom, "No overload matches this call:

I tried to work with the types of the documentation, but not sure how and where to place it ...
FYI: In my case, I use interceptors and axios and instance are imported from another file ... guess that does not make a difference ... just in case.

If I just use it wrong, could somebody please give me an example for this case?

Thanks in advance
Stefan

```
{
	"resource": "/home/.../src/store/api/clm.api.ts",
	"owner": "typescript",
	"code": "2769",
	"severity": 8,
	"message": "No overload matches this call.\n  Overload 1 of 3, '(url: string, config?: AxiosRequestConfig<any> | undefined): UseAxiosReturn<any>', gave the following error.\n    Type 'AxiosInstance' has no properties in common with type 'AxiosRequestConfig<any>'.\n  Overload 2 of 3, '(url: string, instance?: AxiosInstance | undefined): UseAxiosReturn<any>', gave the following error.\n    Argument of type 'import(\"/home/.../node_modules/axios/index\").AxiosInstance' is not assignable to parameter of type 'import(\"/home/.../node_modules/@vueuse/integrations/node_modules/axios/index\").AxiosInstance'.\n      Types of property 'defaults' are incompatible.\n        Type 'AxiosRequestConfig' is not assignable to type 'AxiosDefaults<any>'.\n          Property 'headers' is optional in type 'AxiosRequestConfig' but required in type 'AxiosDefaults<any>'.",
	"source": "ts",
	"startLineNumber": 38,
	"startColumn": 140,
	"endLineNumber": 38,
	"endColumn": 143
}]
```

**Comment by hamburgerdog** [comment] 2021-11-18 07:44
Hi,Stefan 😄 

> `Property 'headers' is optional in type 'AxiosRequestConfig' but required in type 'AxiosDefaults<any>'.` 

From inside the error message, it looks like your problem is caused by a typescript type error. Did you make changes to the type of the axios instance you imported from another file or interceptors? Have you tried re-creating an instance in the same way as the demo to see if it solves the problem? Perhaps you can show your source code to provide more information to help solve this problem.

For the type definition of useAxios() you can see this page : https://vueuse.org/integrations/useaxios/#type-declarations
You should make sure that your parameters match the type restrictions of this function

**Comment by sdoerger** [comment] 2021-11-18 09:46
Hi Xjosiah, thanks for responding.

Uhm, not sure. So in api an axios instance is created. See the code beleow
Seems close to to useAxios example.

```
import axios from 'axios';
import router from '@/router';

// This is da way (for old and new api calls)
const api = axios.create({
  baseURL: '/api',
  timeout: 3000,
});

// interceptors are called before every request
api.interceptors.request.use(
  function (config) {
    const token = localStorage.getItem('accessToken');
    if (token) {
      config.headers.Authorization = 'Bearer ' + token;
    }
    return config;
  },
  function (error) {
    return Promise.reject(error);
  }
);

// interceptors are called before every response
api.interceptors.response.use(
  function (response) {
    return response;
  },
  function (error) {
    // request was made with server response
    if (typeof error.response !== 'undefined') {
      // logout
      if (error.response.status === 401) {
        router.push('/');
      }
      // request was made without server response
    }

    return Promise.reject(error);
  }
);

export { api };
```

I try now AxiosRequestConfig as type for config, to see what happens.

**Comment by antfu** [comment] 2021-11-25 02:53
We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.

**Closed by antfu** 2021-11-25 02:53 UTC
