### ISSUE TITLE
无法同时更新两个路由参数

### ISSUE THREAD

**Issue by w1972046143** [vueuse/vueuse#2124] opened 2022-08-25 08:58 UTC
### Describe the bug

const unitId = allUtil.useRouteQuery('unitId') 
const flrId = allUtil.useRouteQuery('flrId')   

unitId.value = unit.id.toString()
flrId.value = floorId.toString()
**这样写只能更新flrId这个路由参数**

**但是如果把其中一个改为宏任务,两个参数才能都得到更新**
  unitId.value = unit.id.toString()
  setTimeout(()=>{
    flrId.value = floorId.toString()
  },0)

### Reproduction

..

### System Info

```Shell
..
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment] 2022-08-25 19:09
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2022-08-25 19:09 UTC
