### ISSUE TITLE
useWebWorker execution exception

### ISSUE THREAD

**Issue by CatsAndMice** [vueuse/vueuse#2406] opened 2022-11-08 12:27 UTC
### Describe the bug

```html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>

<body>
  <script src="https://unpkg.com/vue@3/dist/vue.global.js"></script>
  <script src="https://unpkg.com/@vueuse/core"></script>
  <script id="worker" type="app/worker">
        console.log(1)
        self.addEventListener('message', function (e) {
            console.log(e)
            self.postMessage('无语')
        })
      
    </script>
  <script>
    window.onload = () => {
      const workerScript = document.getElementById('worker');
      const textContent = workerScript.textContent;
      const blob = new Blob([textContent])
      const url = URL.createObjectURL(blob)
      const {data} =  VueUse.useWebWorker(() => {
        return new Worker(url)
      })
      console.log(data.value);
    }
  </script>
</body>
</html>. 
```html
使用`useWebWorker`来运行一个`Worker`失败,`data.value`始终没有改变

### Reproduction

<script src="https://unpkg.com/@vueuse/core"></script>

### System Info

```Shell
browsers
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment] 2022-11-09 01:08
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2022-11-09 01:08 UTC
