### ISSUE TITLE
Vueuse makes Nuxt stop updating

### ISSUE THREAD

**Issue by Ricklin90085** [vueuse/vueuse#637] opened 2021-07-19 14:45 UTC
I'm trying to use `@vueuse/core` with `@nuxtjs/composition-api` in my Nuxt project.
But when I `import { onClickOutside } from '@vueuse/core'` to my component, which will stop updating without any error message.
I have no idea how to track this problem.

### Reproduction Link
[Codesandbox](https://codesandbox.io/s/nuxt-vueuse-22dxz?file=/pages/index.vue)

### Steps to reproduce
1. Click the **Open Button** will see the div `Now you can see me` show and `console.log('updated')` either.
2. Remove the comment of vueuse
```javascript
// import { onClickOutside } from '@vueuse/core'

// onClickOutside(divRef, () => {
//   console.log('onClickOutside')
//   state.value = false
// })
```
6. Click the **Open Button** will see the div `Now you can see me` isn't show and console.log('updated') either.

Thanks for your help. :)

**Comment by TonyPythoneer** [comment] 2021-07-19 17:54
Hi @Ricklin90085 

I want to help you but I can't install your repo in my computer. Please check your repo.


```
npm WARN tar ENOENT: no such file or directory, open '/home/tony/tony/test-nuxt-vueuse/node_modules/.staging/rxjs-b753abfb/internal/operators/retryWhen.js.map'
npm WARN tar ENOENT: no such file or directory, open '/home/tony/tony/test-nuxt-vueuse/node_modules/.staging/rxjs-b753abfb/operator/retryWhen.js.map'
npm WARN tar ENOENT: no such file or directory, open '/home/tony/tony/test-nuxt-vueuse/node_modules/.staging/rxjs-b753abfb/operators/retryWhen.js.map'
npm WARN tar ENOENT: no such file or directory, open '/home/tony/tony/test-nuxt-vueuse/node_modules/.staging/rxjs-b753abfb/_esm2015/internal/util/root.js.map'
npm WARN tar ENOENT: no such file or directory, open '/home/tony/tony/test-nuxt-vueuse/node_modules/.staging/rxjs-b753abfb/_esm5/internal/util/root.js.map'
npm WARN tar ENOENT: no such file or directory, open '/home/tony/tony/test-nuxt-vueuse/node_modules/.staging/rxjs-b753abfb/internal/util/root.js.map'
npm WARN tar ENOENT: no such file or directory, open '/home/tony/tony/test-nuxt-vueuse/node_modules/.staging/rxjs-b753abfb/util/root.js.map'
npm WARN tar ENOENT: no such file or directory, open '/home/tony/tony/test-nuxt-vueuse/node_modules/.staging/rxjs-b753abfb/_esm2015/internal/Rx.js.map'
npm WARN tar ENOENT: no such file or directory, open '/home/tony/tony/test-nuxt-vueuse/node_modules/.staging/rxjs-b753abfb/_esm5/internal/Rx.js.map'
npm WARN tar ENOENT: no such file or directory, open '/home/tony/tony/test-nuxt-vueuse/node_modules/.staging/rxjs-b753abfb/internal/Rx.js.map'
npm WARN tar ENOENT: no such file or directory, open '/home/tony/tony/test-nuxt-vueuse/node_modules/.staging/rxjs-b753abfb/Rx.js.map'
npm WARN tar ENOENT: no such file or directory, open '/home/tony/tony/test-nuxt-vueuse/node_modules/.staging/rxjs-b753abfb/bundles/rxjs.umd.js.map'
```

**Comment by Ricklin90085** [comment] 2021-07-20 02:14
@TonyPythoneer Thanks for reply!
I clone the repo and reinstall it. The installation process went smoothly without any error messages.🤔

Here is the information of my computer:
- MacBook Pro (13-inch, M1, 2020)
- macOS Big Sur: 11.4
- node version: 16.1.0
- yarn version: 1.22.10

And I tried to search the solution of the error message you provided. Maybe delete `yarn.lock` and run `yarn install` again will help.

Hope it can help you solve the problem.

**Comment by Ricklin90085** [comment] 2021-07-22 03:05
Change reproduction link to codesandbox.

**Comment by CapitaineToinon** [comment] 2021-07-22 21:02
At first, I wasn't able to install `@vueuse`. I fixed it after finding [this issue on the `@nuxtjs/composition-api` repo](https://github.com/vueuse/vue-demi/issues/76) and installed `v0.25.0` of `@nuxtjs/composition-api` and now I have the same isse with Nuxt just not updating anymore. 

So I am not sure if the issue is releated to `@vueuse` or `@nuxtjs/composition-api`.

**Comment by antfu** [comment] 2021-07-22 21:41
Please try https://github.com/vuejs/composition-api/releases/tag/v1.0.4

**Comment by CapitaineToinon** [comment] 2021-07-22 21:59
`v1.0.4` seems to have fixed my use case with `useDark` but my other page relying on `useAsync` still doesn't update. 

```vue
<template>
  <!-- this will never show because page becomming truthy doesn't seems to trigger an update -->
  <div v-if="page" class="prose-lg" v-html="$md.render(page.body)"></div>
</template>

<script lang="ts">
import { defineComponent, useAsync, useContext } from "@nuxtjs/composition-api";

export default defineComponent({
  setup() {
    const { $strapi } = useContext();
    const page = useAsync(() => $strapi.find("about"));
    return { page };
  },
});
</script>
``` 

But if I stop using `useDark` (and just force a theme to the user) then the code above works.

**Comment by antfu** [comment] 2021-07-22 22:04
@CapitaineToinon try upgrade your lock and do a clean install (make share only one version of `@vue/composition-api` is installed

**Comment by CapitaineToinon** [comment] 2021-07-22 22:11
Problem still here after typing these commands

```zsh
$ rm -rf node_modules/
$ rm -rf .nuxt
$ npm i
[...]
added 2091 packages, and audited 2092 packages in 25s
$ cat node_modules/@vue/composition-api/package.json | grep version
  "version": "1.0.4",
    "version": "yarn changelog && yarn update-readme && git add CHANGELOG.md README.*",
    "release": "yarn version && yarn test && yarn publish --non-interactive && git push --follow-tags",
```

I'm not sure how to check if multiple versions of `@vue/composition-api` are installed other than checking if only one folder with that name exists, which is the case.

**Comment by antfu** [comment] 2021-07-22 22:12
Try `npm why @vue/composition-api`

**Comment by CapitaineToinon** [comment] 2021-07-22 22:19
Ah yeah nevermind

```zsh
@vue/composition-api@1.0.3
node_modules/@nuxtjs/composition-api/node_modules/@vue/composition-api
  @vue/composition-api@"1.0.3" from @nuxtjs/composition-api@0.25.0
  node_modules/@nuxtjs/composition-api
    @nuxtjs/composition-api@"^0.25.0" from the root project

@vue/composition-api@1.0.4
node_modules/@vue/composition-api
  dev @vue/composition-api@"^1.0.4" from the root project
  peer @vue/composition-api@"^0.5.0 || ^1.0.0-beta.17 || ^1.0.0-rc.5" from swrv@0.9.4
  node_modules/swrv
    swrv@"^0.9.4" from the root project
  peerOptional @vue/composition-api@"^1.0.0-rc.1" from vue-demi@0.11.2
  node_modules/vue-demi
    vue-demi@"*" from @vueuse/core@5.1.4
    node_modules/@vueuse/core
      @vueuse/core@"^5.1.4" from the root project
    vue-demi@"*" from @vueuse/shared@5.1.4
    node_modules/@vueuse/shared
      @vueuse/shared@"5.1.4" from @vueuse/core@5.1.4
      node_modules/@vueuse/core
        @vueuse/core@"^5.1.4" from the root project
```

Sorry I'm not used to contributing and testing early versions, how can I enforce 1.0.4? I thought editing the lock by hand was a bad practice but I see no other way.

**Comment by antfu** [comment] 2021-07-22 22:24
Try `npm upgrade`? I know `yarn` and `pnpm` allow you to force version of packages, but not sure how to deal it properly with npm. (or maybe remove lock and node_modules together?)

**Comment by CapitaineToinon** [comment] 2021-07-22 22:34
I'm all good thanks to `@nuxtjs/composition-api@0.25.1` being released a few minutes ago but the issue is still here. 

```zsh
@vue/composition-api@1.0.4
node_modules/@vue/composition-api
  dev @vue/composition-api@"^1.0.4" from the root project
  peer @vue/composition-api@"^0.5.0 || ^1.0.0-beta.17 || ^1.0.0-rc.5" from swrv@0.9.4
  node_modules/swrv
    swrv@"^0.9.4" from the root project
  peerOptional @vue/composition-api@"^1.0.0-rc.1" from vue-demi@0.11.2
  node_modules/vue-demi
    vue-demi@"*" from @vueuse/core@5.1.4
    node_modules/@vueuse/core
      @vueuse/core@"^5.1.4" from the root project
    vue-demi@"*" from @vueuse/shared@5.1.4
    node_modules/@vueuse/shared
      @vueuse/shared@"5.1.4" from @vueuse/core@5.1.4
      node_modules/@vueuse/core
        @vueuse/core@"^5.1.4" from the root project
  @vue/composition-api@"^1.0.4" from @nuxtjs/composition-api@0.25.1
  node_modules/@nuxtjs/composition-api
    @nuxtjs/composition-api@"^0.25.0" from the root project
```

May be worth noting that in the code I showed in [here](https://github.com/vueuse/vueuse/issues/637#issuecomment-885262632) displayed the data correctly when the page is rendered with SSR but not when navigated on the client from another page.

**Comment by Ricklin90085** [comment] 2021-07-23 02:50
Hi @antfu Thanks for reply.
I have upgraded the`@nuxtjs/composition-api` version to `0.25.1`.
```
"@nuxtjs/composition-api@^0.25.1":
  version "0.25.1"
  resolved "https://registry.yarnpkg.com/@nuxtjs/composition-api/-/composition-api-0.25.1.tgz#9c1658b77c7a8ae6e86f3d3452f5a0d26d9e1ead"
  integrity sha512-YoRVwt8zmdomYeaRM7AcQ8K7jlz/T3vz6Yn5EBVZqYOuQ6e7b987DBrZFbxr6yCsx5ytaihD+nJyDM8+XPfcOw==
  dependencies:
    "@vue/composition-api" "^1.0.4"
    defu "^5.0.0"
    estree-walker "^2.0.2"
    fs-extra "^9.1.0"
    magic-string "^0.25.7"
    ufo "^0.7.7"
    upath "^2.0.1"
```
But it didn't work. :(
Could you please reopen this issue?
I also upgraded [reproduction](https://codesandbox.io/s/nuxt-vueuse-22dxz?file=/pages/index.vue)'s `@nuxtjs/composition-api` version, hope can help you. 🙏

**Comment by nonlinearcom** [comment] 2021-07-27 17:52
Hi, same here on node v14.17.3 and

```
"nuxt": "^2.15.7",
"@nuxtjs/composition-api": "^0.25.2",
"@vueuse/core": "^5.2.0",
```

Does anyone know up to which version should we temporarily  downgrade in order to restore these functionalities? 
Thanks!

**Comment by nonlinearcom** [comment] 2021-07-27 20:05
...here is another reproduction test, with and without composables 🤔

**Comment by antfu** [comment] 2021-07-28 12:16
Might be related to https://github.com/nuxt-community/composition-api/pull/525

**Comment by danielroe** [comment] 2021-07-28 12:37
Fix released in `0.26.0` - let me know if that doesn't work for you.

**Comment by nonlinearcom** [comment] 2021-07-28 12:42
Fixed, thanks @danielroe!

**Comment by CapitaineToinon** [comment] 2021-07-28 12:54
Cloned and tested with `yarn link`, seems to have fixed the issue indeed, thanks 👍

**Closed** 2021-07-28 12:57 UTC

**Comment by Ricklin90085** [comment] 2021-07-28 18:09
@danielroe
It works! Thanks for fix. :D
@antfu 
Thanks for pay attention to this issue. :D
