### ISSUE TITLE
[feature] useNotification : add Notification for broswer

### ISSUE THREAD

**Issue by MisaelMa** [vueuse/vueuse#458] opened 2021-04-16 20:40 UTC
I wanted to use it to make it easier to use browser notifications but didn't see it being available and I did it with another library

**Comment by wheatjs** [comment] 2021-04-18 01:42
Seems like a duplicate of #328, do you have an idea for how you want this API to work?

**Comment by wheatjs** [comment] 2021-05-12 06:15
Moving discussion back to #328 as this issue hasn't had any activity and is a duplicate

**Closed by wheatjs** 2021-05-12 06:15 UTC
