### ISSUE TITLE
`useRouteQuery` can only custom deserialize but cannot custom serialize

### ISSUE THREAD

**Issue by matthew-dean** [vueuse/vueuse#3970] opened 2024-05-14 21:40 UTC
### Clear and concise description of the problem

I stumbled into this because I expected that for sure `useRouteQuery` would allow deserialization AND serialization transforms in order to store any arbitrary state in the query string.

In my case, I had local refs for `startDate` and `endDate` as JavaScript dates. I decided I wanted to persist these dates into the query string. The thing is, `useRouteQuery` only allows one-way transforms. That is, if I wanted to store the default value as a `YYYY-MM-DD`, and then deserialize to `Date`, that seems fine. However, this utility is extremely limited, because I could not control serializing the date BACK into the querystring. (It just defaults to JavaScript's crap date serialization i.e. `?startDate=Mon+Apr+15+2024+14:29:33+GMT-0700+(Pacific+Daylight+Time)`)

### Suggested solution

Allow two-way transforms i.e. serialization. I'd suggest something like:

```ts
useRouteQuery(
   'startDate',
    '2024-05-08',
    {
      from(value: string) { // or fromQueryString()? or just transform() how it is now?
        return dayjs(value).toDate()
      }
      to(value: Date) { // or toQueryString()?  or transformTo()?
        return dayjs(value).format('YYYY-MM-DD')
      }
    }
```

### Alternative

I don't see any alternatives immediately, other than using a different library or a drastically different approach.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by jpritzkau-eepos** [comment] 2024-05-25 11:38
Custom serializers already exist in other utilities, such as [`useStorage`](https://vueuse.org/core/useStorage/). This would also be nice for boolean serialization.

```js
const create = useRouteQuery<boolean>("create", false, {
  serializer: {
    read: (v: string) => v === null,
    write: (v: boolean) => v ? null : undefined
  }
})

create.value = false; // /
create.value = true;  // /?create
```

**Comment by jpritzkau-eepos** [comment] 2024-05-25 11:44
`useStorage` even defines default serializers based on the type of the default value. I think that would work well here too.

**Comment by jpritzkau-eepos** [comment] 2024-05-25 11:47
Isn't this a duplicate of #3929?

**Comment by ilyaliao** [comment] 2024-12-21 02:36
I guess the issue here has been resolved, so I will close it. If not, feel free to reopen it.

**Closed by ilyaliao** 2024-12-21 02:36 UTC
Labels: enhancement
