### ISSUE TITLE
I don't know why vueuse can not work on my mac!!!!Please help!!!!

### ISSUE THREAD

**Issue by KBKUN024** [vueuse/vueuse#1432] opened 2022-03-17 10:22 UTC
### Describe the bug

I'm following the steps of vueuse documentation,but I find that code can not work on my mac,I really don't know why, my code is obviously the same as the documentation.There are some screenshots which are I am facing.
<img width="346" alt="image" src="https://user-images.githubusercontent.com/54589019/158788408-f7cbc6aa-c9d7-4ad4-af94-4086245046d2.png">
<img width="238" alt="image" src="https://user-images.githubusercontent.com/54589019/158788450-b4dfd7a3-0a8e-40b0-93ba-fd2f5d1a8e3c.png">
You can see the codes is in documentation,but when I move my mouseponiter into browser,the value of x and y are not change,this is very wired.

### Reproduction

Sorry,but I put some screenshots above.

### System Info

```Shell
Nothing output.All normal.
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by KBKUN024** [comment] 2022-03-17 10:23
<img width="310" alt="image" src="https://user-images.githubusercontent.com/54589019/158788920-ef8b2a9c-311b-4549-865e-3e071d4095ee.png">
These are my dependencies.

**Comment by antfu** [comment] 2022-03-17 10:29
We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.

**Comment by antfu** [comment] 2022-03-17 10:30
Try https://github.com/antfu/vitesse

**Closed by antfu** 2022-03-17 10:29 UTC

**Comment by KBKUN024** [comment] 2022-03-17 10:31
> Try https://github.com/antfu/vitesse

ok,thank you ! I will try it now!!!
