### ISSUE TITLE
useWindowSize添加的事件貌似不会在组件卸载后被移除

### ISSUE THREAD

**Issue by daLeiStrive** [vueuse/vueuse#2157] opened 2022-09-02 06:30 UTC
### Clear and concise description of the problem

useWindowSize 添加的事件不会在当前组件卸载后移除window.resize

### Suggested solution

useWindowSize 添加的事件应该在当前组件卸载后移除window.resize

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by daLeiStrive** [comment] 2022-09-02 06:39
在class中使用的

**Comment by antfu** [comment] 2022-09-02 10:25
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2022-09-02 10:25 UTC
Labels: enhancement
