### ISSUE TITLE
multiple useFullscreen  do not work properly，Fullscreen specified element is bad

### ISSUE THREAD

**Issue by yoonaiorlim** [vueuse/vueuse#2322] opened 2022-10-14 04:41 UTC
### Describe the bug

![1665719986](https://user-images.githubusercontent.com/78140083/195762307-88a7cbc3-e270-4836-8199-d72271e98200.jpg)

### Reproduction

123

### System Info

```Shell
System:
    OS: Windows 10 10.0.19041
    CPU: (4) x64 Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz
    Memory: 18.73 GB / 31.46 GB
  Binaries:
    Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1.0)
    Internet Explorer: 11.0.19041.1
  npmPackages:
    vue: ^3.2.37 => 3.2.40
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by wheatjs** [comment] 2022-10-14 06:02
We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://antfu.me/posts/why-reproductions-are-required) to reopen the issue. Thanks.

**Closed** 2022-10-14 06:03 UTC
