### ISSUE TITLE
Feature-suggestion: integrate body-scroll-lock (or a similar implementation)

### ISSUE THREAD

**Issue by Mvsvh** [vueuse/vueuse#534] opened 2021-05-25 14:26 UTC
## Why this would be useful

When opening modals or pop-ups the body container should not be scrollable (otherwise the user get's confused when the modal is closed and the user finds himself somewhere else. There are several CSS/js ways to achieve this, but I think it would be great to integrate this as a composition function in vueuse to reduce mental load and add yet another great utility to this awesome library.

## Suggestions for the implementation
This is the package I am currently using in my project:

[body-scroll-lock](https://www.npmjs.com/package/body-scroll-lock)

It already has a nice API that integrates well into programming with the Composition API. I did some research to find it (usually I find these things in vueuse). So for any future developers I thought it would be cool to find it right here in vueuse in one way or another...

I am not sure wether this is too specific. Interested to hear your thoughts on this!

**Comment by wheatjs** [comment] 2021-05-29 01:25
Looks like a duplicate of #488. Will close here and suggest discussing there instead 🙂

**Closed** 2021-05-29 01:25 UTC

**Comment by jd-solanki** [comment] 2022-06-26 18:48
I am also waiting for this. Sad see it won't get added in VueUse. Moreover, we already have [`useConfirmDialog`](https://vueuse.org/core/useConfirmDialog/) which will be easy to use combined.
