### ISSUE TITLE
[Docs]: linking to category filter not working

### ISSUE THREAD

**Issue by mtdvlpr** [vueuse/vueuse#4306] opened 2024-10-27 06:58 UTC
### Describe the bug

When I want to share the functions list of a certain category, I'll send the filtered url, but when you open it, the list isn't filtered. When you press the filter manually it first removes the filter from the url and then you have to press again to get the desired filter working.

### Reproduction

https://vueuse.org/functions.html#category=Watch

### System Info

```Shell
Firefox - Android
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by CofCat456** [comment] 2024-10-27 14:24
Developing locally doesn't seem to have this problem

**Comment by babu-ch** [comment] 2024-11-01 12:17
I tried serve and was able to reproduce it.
`nr docs:build && nr docs:serve`

If you get the query with onMounted, the discrepancy will be eliminated and it may be cured.

**Comment by ilyaliao** [comment] 2024-12-24 14:27
Duplicate of #4224, let's move the discussion there.

**Closed** 2024-12-24 14:27 UTC
Labels: duplicate

**Comment by babu-ch** [comment] 2024-12-24 14:30
@ilyaliao 
Oh, coincidentally I just created a PR 😲

**Comment by ilyaliao** [comment] 2024-12-24 15:05
> @ilyaliao Oh, coincidentally I just created a PR 😲

I'm sorry about that! Thank you for your contribution. Let’s see how we can resolve this issue.
