### ISSUE TITLE
cant use in quasar project

### ISSUE THREAD

**Issue by ahmadem** [vueuse/vueuse#1998] opened 2022-07-26 23:06 UTC
### Describe the bug

Hello
I want to use vElementVisibility as a directive in a quasar project. But I have the following problem. What could be the reason?
Thankfu
![Screenshot (57)](https://user-images.githubusercontent.com/37769137/181127121-cce9c17b-67eb-4990-a5d1-05aa1819490c.png)
l

### Reproduction

none

### System Info

```Shell
System:
    OS: Windows 10 10.0.19043
    CPU: (4) x64 Intel(R) Core(TM) i5-2450M CPU @ 2.50GHz
    Memory: 704.90 MB / 5.94 GB
Binaries:
    Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.13.2 - C:\Program Files\nodejs\npm.CMD
Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (103.0.1264.71)
    Internet Explorer: 11.0.19041.1566
npmPackages:
    @vueuse/components: ^8.9.4 => 8.9.4
    @vueuse/core: ^8.9.4 => 8.9.4
    vue: ^3.2.37 => 3.2.37
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment] 2022-07-27 06:31
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2022-07-27 06:31 UTC
