### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by chenmin-xx** [vueuse/vueuse#4023] opened 2024-06-06 08:49 UTC
## Syntax error, you shouldn't use "const A extends ..."

```javascript

export function makeDestructurable<
  T extends Record<string, unknown>,
  const A extends readonly any[],
>(obj: T, arr: A): T & A {
  if (typeof Symbol !== 'undefined') {
    const clone = { ...obj }

    Object.defineProperty(clone, Symbol.iterator, {
      enumerable: false,
      value() {
        let index = 0
        return {
          next: () => ({
            value: arr[index++],
            done: index > arr.length,
          }),
        }
      },
    })

    return clone as T & A
  }
  else {
    return Object.assign([...arr], obj) as unknown as T & A
  }
}
```

### Reproduction

null

### System Info

```Shell
null
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by liuhanqu** [comment] 2024-06-07 01:47
try to bump your `typescript` version

**Comment by chenmin-xx** [comment] 2024-06-07 02:19
Sorry, my version is 4.4.5, it's true that my version is too low 😂 @liuhanqu

**Comment by brenoepics** [comment] 2024-06-09 05:07
duplicate of https://github.com/vueuse/vueuse/issues/4006

**Closed** 2024-06-11 13:29 UTC
