### ISSUE TITLE
useScroll and Nuxt 2

### ISSUE THREAD

**Issue by othy54** [vueuse/vueuse#940] opened 2021-11-19 23:13 UTC
Hi !

I wanna just use useScroll in my Nuxt 2 project but don't understand why values don't update

```
<script setup>
import { useScroll } from '@vueuse/core'
import { ref } from '@vue/composition-api'

export default {
 setup() {
    const el = ref(null)
    const { x, y, isScrolling, arrivedState } = useScroll(el)

    return {
      x,
      y,
      arrivedState,
      isScrolling,
    }
  },
}
</script>
```

Thanks !

**Comment by webfansplz** [comment] 2021-11-20 01:55
Hi.Can you provide a mini repo ?

**Comment by antfu** [comment] 2021-11-20 19:25
We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.

**Closed by antfu** 2021-11-20 19:25 UTC

**Comment by othy54** [comment] 2021-12-03 16:06
Or can someone give me an exemple pour useScroll on Nuxt 2 ?

**Comment by yassilah** [comment] 2021-12-04 20:47
Just looking at it it seems you forgot to add your `el` ref in your return statement.

**Comment by wheatjs** [comment] 2021-12-04 23:08
You cannot use both `<script setup>` and `export default { setup(){} }` in the same vue component.

Either change it to this
```html
<script setup>
import { useScroll } from '@vueuse/core'
import { ref } from '@vue/composition-api'

const el = ref(null)
const { x, y, isScrolling, arrivedState } = useScroll(el)
}
</script>
```
or remove the `setup` attribute from the script tag
