### ISSUE TITLE
support vue2.7.0

### ISSUE THREAD

**Issue by yanbowe** [vueuse/vueuse#1740] opened 2022-07-04 03:41 UTC
### Clear and concise description of the problem

now，Does not support  vue2.7.0
![image](https://user-images.githubusercontent.com/43030980/177077675-549fd687-64b7-4c63-bec7-5004e768c4ef.png)

### Suggested solution

support vue2.7.0

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment] 2022-07-04 05:25
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2022-07-04 05:25 UTC
Labels: enhancement
