### ISSUE TITLE
There are two active items in the side menu

### ISSUE THREAD

**Issue by cawa-93** [vueuse/vueuse#472] opened 2021-04-26 20:26 UTC
### Reproduction:

1. Open https://vueuse.org/core/useActiveElement/
2. Click on any menu item. In my example it's `useEventListener`

### Actual behaviour:
`useActiveElement` and `useEventListener` in sidebar are highlighted together. 

![зображення](https://user-images.githubusercontent.com/1662812/116146101-a31c9d00-a6cd-11eb-81d3-69f1f59f18ff.png)

### Environment 
- Windows 10
- Firefox 89.0b4

**Comment by wheatjs** [comment] 2021-04-26 20:54
Duplicate of #343

**Closed by wheatjs** 2021-04-26 20:54 UTC
