### ISSUE TITLE
BUG | `useSortable` | Cannot find module 'async-validator'

### ISSUE THREAD

**Issue by jamols09** [vueuse/vueuse#4412] opened 2024-12-19 17:52 UTC
### Describe the bug

Install vueuse integrations

```js
<script setup lang="ts">
import { ref } from "vue";
import { useSortable } from "@vueuse/integrations";

const { option } = useSortable(el, list, {
	animation: 150,
});
</script>

Error
`Cannot find package 'async-validator' imported from C:\laragon\www\PERSONAL\cv-builder\node_modules\@vueuse\integrations\index.mjs`


### Reproduction

https://stackblitz.com/edit/vitejs-vite-rptfks?file=src%2FApp.vue

### System Info

```Shell
System:
    OS: Windows 11 10.0.22621
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
    Memory: 14.11 GB / 31.95 GB
  Binaries:
    Node: 20.11.1 - C:\laragon\bin\nodejs\node-v20.11.1-win-x64\node.EXE
    Yarn: 1.22.22 - C:\laragon\bin\nodejs\node-v20.11.1-win-x64\yarn.CMD
    npm: 10.2.4 - C:\laragon\bin\nodejs\node-v20.11.1-win-x64\npm.CMD
    pnpm: 8.15.3 - C:\laragon\bin\nodejs\node-v20.11.1-win-x64\pnpm.CMD
  Browsers:
    Chrome: 131.0.6778.141
    Edge: Chromium (129.0.2792.52)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @vueuse/integrations: ^12.0.0 => 12.0.0
    @vueuse/nuxt: ^12.0.0 => 12.0.0
    vue: latest => 3.5.13
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment] 2024-12-20 04:12
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed** 2024-12-20 04:12 UTC

**Comment by alexmnv** [comment] 2025-06-20 05:24
To solve the issue you need to import from submodule:
```
// import { useSortable } from "@vueuse/integrations";

import { useSortable } from "@vueuse/integrations/useSortable";
```
