### ISSUE TITLE
Cannot import  'createReusableTemplate'

### ISSUE THREAD

**Issue by gastrodia** [vueuse/vueuse#3112] opened 2023-05-24 02:14 UTC
### Describe the bug

```vue
<script setup lang="ts">
import { createReusableTemplate } from '@vueuse/core'
console.log(createReusableTemplate)
</script>

<template>
  <h1>hello</h1>
</template>
```

```text
Module '"@vueuse/core"' has no exported member 'createReusableTemplate
```

### Reproduction

https://play.vueuse.org/#N4IgDghgxg1hDmBTAziAXAbVAOwgW0XRADcBXRAWgBNE8BLEAGhGQHtSAnKQtEU7MDHhMQNZFA50wAFzqtsRAGrkABABFadFQAoAFhAA2AMxV1sKgGIdE2KLoCUp5CogqaxRAdZgz8FaVkDOmkATxcDLwB3ZxD2FWlWFUjJaUQVAFVsOg8OZEMVZTSAGToAIw4ISRQVI1YOAtUAJhUAMhUAZhFOAyJdaWkwZDQAemH+QXgAOihWPGGyShp6YaDS4bMaAA9JvAArVABfRhx8HhAAAQXSZERh5H1rKhE2Tm4icaERMQkpWXkiADKD0QVAaiHSN38gWCdBQky6HB6vD6AyGow+Uxmc0u5Gut3ulRB5wAnJMAAzk9bYLY7fYgI4nAhEHGIPHDGbWZ7sLhnDFfFA-GRyBS8ADCrAiiCgf3MrBMKBu2Fk+UKKnFeDArGQMPkGWhshQCKRIBRgxGYwEQmms2GLLZHMQJPJlI2iG2e0OAF1mEY6AZDWhQABBMBgSYLdCgVIagwQVJEAA8ugAjAA+XSeLwJ4Yp1PPQXSIh0DV1aQqYAqCSIOOIABKrLypX9ABVaGBY6kVAcahxZioAOR2m7suqIfsAHWwk5m2GQZYwGl92EQrZjNcYKnreNX7ZrnpUAF5K9Ya1vGy22x3ENp7PSDgcgA

### System Info

```Shell
*
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by gastrodia** [comment] 2023-05-24 02:16
version is latest (v10.1.0)

**Comment by gastrodia** [comment] 2023-05-24 02:29
The `createTemplatePromise` same problem exists

**Comment by Alfred-Skyblue** [comment] 2023-05-24 03:18
This problem is caused by the low version of vueuse in vueuse-playground.

**Comment by wheatjs** [comment] 2023-05-26 16:20
Merged. Let me know if this fixes the issue

**Comment by Alfred-Skyblue** [comment] 2023-06-20 03:54
> Merged. Let me know if this fixes the issue

Great, solved.

**Closed by Alfred-Skyblue** 2023-06-20 03:54 UTC
